# Generated by Django 3.1.8 on 2021-08-23 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boxapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='phone_number',
            field=models.IntegerField(blank=True, max_length=250),
        ),
    ]
