# Generated by Django 3.1.8 on 2021-08-23 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boxapp', '0002_auto_20210823_1253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='phone_number',
            field=models.CharField(blank=True, max_length=16),
        ),
    ]
